# docker-compose.yml

services:
  db:
    image: postgres:15
    container_name: inventario_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: inventario_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: inventario_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_NAME=inventario_db
      - PORT=3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: inventario_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: